### PR TITLE
Added silent mode for inject and is32bit (Closes #33)

### LINKED ISSUE #33: Use stderr instead of MessageBox...

### PR DESCRIPTION
**Pull request by danielgindi**
(opt-in to stderr instead of MessageBox)

### CODE REVIEW

**Comment by jbremer** [comment]
While at it, do you mind providing a PR for Cuckoo to opt-in to this behavior? :-)

**Comment by danielgindi** [comment]
I'm still experimenting with it - not sure how to go about it...

Cuckoo should probably know how to parse the `stderr` for errors starting with `[-] Error` and add those as extra error info.

**Comment by jbremer** [comment]
Hi, I'm currently addressing a number of `monitor`-related issues, one of them being this one.
Although I'm not finished yet with the related changes, please find the following commits that make up for a headstart with regards to solving this issue; https://github.com/cuckoosandbox/monitor/commit/8be4bf30e224f8801e4572a52f0a078572a021c1 https://github.com/jbremer/cuckoo/commit/d1c1fe76a3fe07ec2ce1ddfccc0e0ad21cb0d289.
Once all has been properly integrated and pushed out I'll be closing this PR. Thanks for your suggestions & feedback and if you have any more, do let me know ;-)

**Comment by danielgindi** [comment]
Well you should handle `MessageBox(NULL, buf, "inject error", 0);` as well...

**Comment by jbremer** [comment]
Good catch, heh ;-) Thanks.

**Pull request closed without merging**
